using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Tebrazi.Appointments.Domain.Entities;

namespace Tebrazi.Appointments.Persistence.Configurations;

public sealed class AppointmentConfiguration : IEntityTypeConfiguration<Appointment>
{
    public void Configure(EntityTypeBuilder<Appointment> builder)
    {
        builder.ToTable("appointments");

        builder.HasKey(a => a.Id);
        builder.Property(a => a.Id).HasColumnName("id").HasMaxLength(36).ValueGeneratedNever();

        // Cross-module keys, no navigations — clinics and clinic patients belong to Clinics,
        // users to Identity. Both are read through published ports.
        builder.Property(a => a.ClinicId).HasColumnName("clinic_id").HasMaxLength(36).IsRequired();
        builder.Property(a => a.PhysicianId).HasColumnName("physician_id").HasMaxLength(36).IsRequired();
        builder.Property(a => a.PatientUserId).HasColumnName("patient_user_id").HasMaxLength(36).IsRequired();
        builder.Property(a => a.SubprofileId).HasColumnName("subprofile_id").HasMaxLength(36);
        builder.Property(a => a.ClinicPatientId).HasColumnName("clinic_patient_id").HasMaxLength(36);

        builder.Property(a => a.Status)
            .HasColumnName("status").HasConversion<string>().HasMaxLength(20).IsRequired();

        builder.Property(a => a.AppointmentType)
            .HasColumnName("appointment_type").HasConversion<string>().HasMaxLength(20).IsRequired();

        builder.Property(a => a.AppointmentDate).HasColumnName("appointment_date").IsRequired();

        // UNBOUNDED, and every one of these five is unbounded ON PURPOSE.
        //
        // The Prisma source declares reason, notes, cancelReason, startTime, endTime and
        // recurringRule as a bare `String?` / `String` with no `@db.VarChar`
        // (server/prisma/schema.prisma:1215-1240) against `provider = "postgresql"`, so every one
        // of them is Postgres `text`. None of the routes validates or truncates any of them:
        // appointments.js:463-480 writes startTime/endTime straight from the body with no format
        // check, :815 writes `cancelReason: reason || null`, and :726 stores the raw `rule`
        // string. A length cap here does not reject the value the way a 400 would — it raises SQL
        // Server error 2628 inside SaveChanges, which surfaces as the route's 500 for a request
        // Node answers 200/201. "HH:mm" is the FORMAT, never the constraint: the slot generator
        // itself emits a three-digit hour past 24:00 rather than wrapping.
        //
        // Safe as nvarchar(max) because none of these six columns is indexed or part of a key.
        // ORDER BY start_time (ITimeSlotStore.ListActiveAsync) and the equality tests in
        // HasBookingAtAsync and GET /available all remain legal on a LOB column.
        builder.Property(a => a.StartTime).HasColumnName("start_time").HasColumnType("nvarchar(max)").IsRequired();
        builder.Property(a => a.EndTime).HasColumnName("end_time").HasColumnType("nvarchar(max)").IsRequired();

        builder.Property(a => a.Reason).HasColumnName("reason").HasColumnType("nvarchar(max)");
        builder.Property(a => a.Notes).HasColumnName("notes").HasColumnType("nvarchar(max)");

        builder.Property(a => a.ConfirmedAt).HasColumnName("confirmed_at");
        builder.Property(a => a.CompletedAt).HasColumnName("completed_at");
        builder.Property(a => a.CancelledAt).HasColumnName("cancelled_at");
        builder.Property(a => a.CancelReason).HasColumnName("cancel_reason").HasColumnType("nvarchar(max)");

        builder.Property(a => a.RecurringRule).HasColumnName("recurring_rule").HasColumnType("nvarchar(max)");

        // Generated by this module as a GUID, never client-supplied, and indexed below — so this
        // one keeps its cap.
        builder.Property(a => a.RecurringGroupId).HasColumnName("recurring_group_id").HasMaxLength(36);

        builder.Property(a => a.DeletedAt).HasColumnName("deleted_at");

        builder.Property(a => a.CreatedAt).HasColumnName("created_at").IsRequired();
        builder.Property(a => a.CreatedBy).HasColumnName("created_by").HasMaxLength(100).IsRequired();
        builder.Property(a => a.UpdatedAt).HasColumnName("updated_at");
        builder.Property(a => a.UpdatedBy).HasColumnName("updated_by").HasMaxLength(100);

        builder.HasIndex(a => a.ClinicId).HasDatabaseName("IX_appointments_clinic_id");
        builder.HasIndex(a => a.PhysicianId).HasDatabaseName("IX_appointments_physician_id");
        builder.HasIndex(a => a.PatientUserId).HasDatabaseName("IX_appointments_patient_user_id");
        builder.HasIndex(a => a.ClinicPatientId).HasDatabaseName("IX_appointments_clinic_patient_id");
        builder.HasIndex(a => a.AppointmentDate).HasDatabaseName("IX_appointments_appointment_date");
        builder.HasIndex(a => a.Status).HasDatabaseName("IX_appointments_status");

        // The workhorse index: the day view, the queue and the availability check all filter on
        // exactly this pair.
        builder.HasIndex(a => new { a.ClinicId, a.AppointmentDate })
            .HasDatabaseName("IX_appointments_clinic_id_appointment_date");

        // Not in the Prisma index set, but a recurring series is always read as a whole and
        // there is no other path to its siblings.
        builder.HasIndex(a => a.RecurringGroupId).HasDatabaseName("IX_appointments_recurring_group_id");
    }
}

public sealed class TimeSlotConfiguration : IEntityTypeConfiguration<TimeSlot>
{
    public void Configure(EntityTypeBuilder<TimeSlot> builder)
    {
        builder.ToTable("time_slots");

        builder.HasKey(s => s.Id);
        builder.Property(s => s.Id).HasColumnName("id").HasMaxLength(36).ValueGeneratedNever();

        builder.Property(s => s.ClinicId).HasColumnName("clinic_id").HasMaxLength(36).IsRequired();
        builder.Property(s => s.PhysicianId).HasColumnName("physician_id").HasMaxLength(36).IsRequired();

        // day_of_week is a bare Int with NO check constraint in the Prisma source
        // (schema.prisma:1199) and none of the three creating routes range-checks it, so 7, 99 and
        // -1 are legal stored values that simply never match GET /available's getDay(). Do not add
        // a CHECK here — see the note in TimeSlot.Create.
        builder.Property(s => s.DayOfWeek).HasColumnName("day_of_week").IsRequired();

        // Unbounded for the same reason as the appointment columns: POST /slots writes the body's
        // times verbatim, and the two generation routes can emit a three-digit hour. Neither
        // column is indexed, and ORDER BY start_time stays legal on a LOB column.
        builder.Property(s => s.StartTime).HasColumnName("start_time").HasColumnType("nvarchar(max)").IsRequired();
        builder.Property(s => s.EndTime).HasColumnName("end_time").HasColumnType("nvarchar(max)").IsRequired();
        builder.Property(s => s.SlotDuration).HasColumnName("slot_duration").HasDefaultValue(30).IsRequired();
        builder.Property(s => s.IsActive).HasColumnName("is_active").HasDefaultValue(true).IsRequired();

        builder.Property(s => s.CreatedAt).HasColumnName("created_at").IsRequired();
        builder.Property(s => s.CreatedBy).HasColumnName("created_by").HasMaxLength(100).IsRequired();

        builder.HasIndex(s => s.ClinicId).HasDatabaseName("IX_time_slots_clinic_id");
        builder.HasIndex(s => s.PhysicianId).HasDatabaseName("IX_time_slots_physician_id");
        builder.HasIndex(s => s.DayOfWeek).HasDatabaseName("IX_time_slots_day_of_week");

        // The availability query always narrows by physician and weekday together.
        builder.HasIndex(s => new { s.PhysicianId, s.DayOfWeek, s.IsActive })
            .HasDatabaseName("IX_time_slots_physician_id_day_of_week_is_active");
    }
}
