// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tebrazi.Visits.Persistence;

#nullable disable

namespace Tebrazi.Visits.Persistence.Migrations
{
    [DbContext(typeof(VisitsDbContext))]
    [Migration("20260902220320_InitialVisits")]
    partial class InitialVisits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tebrazi.Visits.Domain.Entities.Investigation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("requested_at");

                    b.Property<string>("ResultNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result_notes");

                    b.Property<string>("ResultUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("result_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubprofileId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("subprofile_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("updated_by");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_investigations_status");

                    b.HasIndex("SubprofileId")
                        .HasDatabaseName("IX_investigations_subprofile_id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("IX_investigations_visit_id");

                    b.ToTable("investigations", (string)null);
                });

            modelBuilder.Entity("Tebrazi.Visits.Domain.Entities.Visit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Assessment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assessment");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("audio_url");

                    b.Property<string>("ChiefComplaint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("chief_complaint");

                    b.Property<string>("ClinicId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("clinic_id");

                    b.Property<string>("ClinicPatientId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("clinic_patient_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.PrimitiveCollection<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diagnosis");

                    b.Property<string>("DiagnosisCodes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diagnosis_codes");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("follow_up_date");

                    b.Property<string>("FollowUpNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("follow_up_notes");

                    b.Property<string>("Objective")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("objective");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("PatientDismissedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("patient_dismissed_at");

                    b.Property<string>("PatientFeedback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("patient_feedback");

                    b.Property<DateTime?>("PatientFeedbackAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("patient_feedback_at");

                    b.Property<string>("PatientUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("patient_user_id");

                    b.Property<string>("PhysicianId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("physician_id");

                    b.Property<string>("Plan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plan");

                    b.Property<string>("RawNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_notes");

                    b.Property<string>("RawTranscript")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_transcript");

                    b.Property<string>("SharedSections")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shared_sections");

                    b.Property<string>("SpecialtyData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("specialty_data");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subjective")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subjective");

                    b.Property<string>("SubprofileId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("subprofile_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("visit_date");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("IX_visits_clinic_id");

                    b.HasIndex("ClinicPatientId")
                        .HasDatabaseName("IX_visits_clinic_patient_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_visits_organization_id");

                    b.HasIndex("PatientUserId")
                        .HasDatabaseName("IX_visits_patient_user_id");

                    b.HasIndex("PhysicianId")
                        .HasDatabaseName("IX_visits_physician_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_visits_status");

                    b.HasIndex("SubprofileId")
                        .HasDatabaseName("IX_visits_subprofile_id");

                    b.HasIndex("VisitDate")
                        .HasDatabaseName("IX_visits_visit_date");

                    b.HasIndex("ClinicId", "VisitDate")
                        .HasDatabaseName("IX_visits_clinic_id_visit_date");

                    b.HasIndex("PatientUserId", "VisitDate")
                        .HasDatabaseName("IX_visits_patient_user_id_visit_date");

                    b.HasIndex("PhysicianId", "Status")
                        .HasDatabaseName("IX_visits_physician_id_status");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("Tebrazi.Visits.Domain.Entities.Investigation", b =>
                {
                    b.HasOne("Tebrazi.Visits.Domain.Entities.Visit", null)
                        .WithMany("Investigations")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tebrazi.Visits.Domain.Entities.Visit", b =>
                {
                    b.Navigation("Investigations");
                });
#pragma warning restore 612, 618
        }
    }
}
