using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace Tebrazi.Visits.Application.ApiModels.Responses;

// ── POST /api/visits/{id}/generate-soap ──────────────────────────────────────

/// <summary>
/// What <c>POST /api/visits/{id}/generate-soap</c> answers with. The endpoint has TWO bodies and
/// they are not variants of one shape: the template fallback (visits.js:925) omits five keys
/// rather than nulling them, so each path has its own record and the handler returns whichever
/// one it produced. Both are HTTP 200.
///
/// <para>The polymorphism attributes carry no <c>$type</c> discriminator — they exist only so the
/// concrete record's properties are written when the value is handed to MVC as this base type.</para>
/// </summary>
[JsonPolymorphic]
[JsonDerivedType(typeof(VisitAiGenerateSoapResponse))]
[JsonDerivedType(typeof(VisitAiSoapTemplateResponse))]
public abstract record VisitAiSoapResult;

/// <summary>
/// The AI path, 11 keys in this order (visits.js:894-909).
/// </summary>
/// <param name="Message">
/// Differs by the request's <c>enhance</c> flag: "SOAP note generated with GPT-4o (enhanced)…"
/// versus "SOAP note generated by AI…". The "GPT-4o" is hard-coded and does not track which
/// provider actually answered.
/// </param>
/// <param name="AiProvider">From the FIRST chat call only; the specialty-extraction call's provider is discarded.</param>
/// <param name="AiUsage">
/// <c>null</c> whenever the usage limiter produced nothing — it fails open. See
/// <see cref="VisitAiUsageResponse"/> for the unlimited-tier shape.
/// </param>
/// <param name="SpecialtyData">
/// <c>mergedSpecialtyData || null</c>. Non-null ONLY when the second AI call parsed JSON and
/// added at least one field, so it is null on a normal run even when the visit HAS stored
/// specialty data. It is not an echo of the column.
/// </param>
/// <param name="SpecialtyKey">The detected template, populated independently of <paramref name="SpecialtyData"/>.</param>
public sealed record VisitAiGenerateSoapResponse(
    string Message,
    string? Subjective,
    string? Objective,
    string? Assessment,
    string? Plan,
    string AiProvider,
    string? AiModel,
    bool Enhanced,
    VisitAiUsageResponse? AiUsage,
    JsonNode? SpecialtyData,
    string? SpecialtyKey) : VisitAiSoapResult;

/// <summary>
/// The AI-failure path, 200 with only 6 keys — <c>aiModel</c>, <c>enhanced</c>, <c>aiUsage</c>,
/// <c>specialtyData</c> and <c>specialtyKey</c> are ABSENT, not null (visits.js:925-932).
/// <c>aiProvider</c> is the literal "template".
/// </summary>
public sealed record VisitAiSoapTemplateResponse(
    string Message,
    string? Subjective,
    string? Objective,
    string? Assessment,
    string? Plan,
    string AiProvider) : VisitAiSoapResult;

/// <summary>
/// The monthly AI quota block the SOAP response carries.
///
/// <para><see cref="Limit"/> and <see cref="Remaining"/> are nullable because the CLINIC tier is
/// unlimited: the Node limiter stores <c>Infinity</c> and <c>JSON.stringify</c> turns it into
/// <c>null</c>, so a CLINIC physician receives
/// <c>{"used":0,"limit":null,"remaining":null,"tier":"CLINIC"}</c> — an object with null numeric
/// members, not a null object. A sentinel number or the string "unlimited" would break the
/// client's arithmetic.</para>
/// </summary>
public sealed record VisitAiUsageResponse(int Used, int? Limit, int? Remaining, string Tier);

// ── POST /api/visits/{id}/suggest-codes ──────────────────────────────────────

/// <summary>
/// <c>POST /api/visits/{id}/suggest-codes</c>. Exactly three keys, in this order. Nothing is
/// persisted — the client stages accepted codes and PUTs them back separately.
/// </summary>
/// <param name="SuggestedCodes">
/// Always an array, never null: it is <c>[]</c> when the model's text did not parse, when every
/// suggestion was filtered out, and when the model genuinely found nothing. The client cannot
/// tell those apart, which is the Node behaviour.
/// </param>
public sealed record VisitAiSuggestCodesResponse(
    IReadOnlyList<VisitAiSuggestedCodeResponse> SuggestedCodes,
    string AiProvider,
    string? AiModel);

/// <summary>
/// One suggestion, already sanitised by the handler: <paramref name="Code"/> upper-cased and cut
/// to 10 characters, <paramref name="Description"/> cut to 200, <paramref name="Confidence"/>
/// clamped to [0,1] and defaulted to 0.5 when the model sent a non-number. Any other key the
/// model emitted is dropped.
/// </summary>
public sealed record VisitAiSuggestedCodeResponse(string Code, string Description, double Confidence);

// ── POST /api/visits/{id}/transcribe ─────────────────────────────────────────

/// <summary>
/// <c>POST /api/visits/{id}/transcribe</c>. Exactly five keys, in this order. The gateway's
/// <c>model</c> ("whisper-1") and <c>costUsd</c> are deliberately not returned, and — unlike
/// generate-soap — there is no <c>aiUsage</c> key even though the limiter ran.
/// </summary>
/// <param name="Transcript">This recording only.</param>
/// <param name="Duration">Whisper's float SECONDS, 0 when absent. Not milliseconds, not an int.</param>
/// <param name="Language">
/// Whisper's own value, which is a full lowercase language NAME ("english"), not the ISO code
/// ("en") the client sent. Do not normalise it — the client renders it verbatim.
/// </param>
/// <param name="FullTranscript">The whole accumulated <c>visit.rawTranscript</c> after the append.</param>
public sealed record VisitAiTranscribeResponse(
    string Transcript,
    double Duration,
    string? Language,
    string Provider,
    string FullTranscript);
