// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tebrazi.Connections.Persistence;

#nullable disable

namespace Tebrazi.Connections.Persistence.Migrations
{
    [DbContext(typeof(ConnectionsDbContext))]
    partial class ConnectionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tebrazi.Connections.Domain.Entities.ConnectionPin", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClinicId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("PhysicianUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("physician_user_id");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("pin");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at");

                    b.Property<string>("UsedByUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("used_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_connection_pins_expires_at");

                    b.HasIndex("PhysicianUserId")
                        .HasDatabaseName("IX_connection_pins_physician_user_id");

                    b.HasIndex("Pin")
                        .HasDatabaseName("IX_connection_pins_pin");

                    b.ToTable("connection_pins", (string)null);
                });

            modelBuilder.Entity("Tebrazi.Connections.Domain.Entities.DoctorPatientConnection", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConnectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("connected_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("initiated_by");

                    b.Property<string>("PatientUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("patient_user_id");

                    b.Property<string>("PhysicianUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("physician_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubprofileId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("subprofile_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("PatientUserId")
                        .HasDatabaseName("IX_doctor_patient_connections_patient_user_id");

                    b.HasIndex("PhysicianUserId")
                        .HasDatabaseName("IX_doctor_patient_connections_physician_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_doctor_patient_connections_status");

                    b.HasIndex("PhysicianUserId", "PatientUserId", "SubprofileId")
                        .IsUnique()
                        .HasDatabaseName("UX_doctor_patient_connections_physician_patient_subprofile")
                        .HasFilter("[subprofile_id] IS NOT NULL");

                    b.ToTable("doctor_patient_connections", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
