// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tebrazi.Prescriptions.Persistence;

#nullable disable

namespace Tebrazi.Prescriptions.Persistence.Migrations
{
    [DbContext(typeof(PrescriptionsDbContext))]
    [Migration("20260902220346_InitialPrescriptions")]
    partial class InitialPrescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tebrazi.Prescriptions.Domain.Entities.Prescription", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Medications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("medications");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("pdf_url");

                    b.Property<string>("PhysicianId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("physician_id");

                    b.Property<string>("RefillNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refill_notes");

                    b.Property<DateTime?>("RefillRequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("refill_requested_at");

                    b.Property<string>("RefillStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("refill_status");

                    b.Property<DateTime?>("SentToPatientAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_to_patient_at");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("signed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubprofileId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("subprofile_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("updated_by");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("PhysicianId")
                        .HasDatabaseName("IX_prescriptions_physician_id");

                    b.HasIndex("RefillStatus")
                        .HasDatabaseName("IX_prescriptions_refill_status");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_prescriptions_status");

                    b.HasIndex("SubprofileId")
                        .HasDatabaseName("IX_prescriptions_subprofile_id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("IX_prescriptions_visit_id");

                    b.ToTable("prescriptions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
